name: Setup
description: Common setup steps used by our workflows
inputs:
 shell:
    description: 'shell to use to run commands'
    required: false
    default: bash
defaults:
    run:
      shell: ${{ inputs.shell }}
runs:
  using: composite
  steps:
    - name: Setup prerequisites
      uses: ./.github/actions/setup-prerequisites

    - name: Install node dependencies
      run: pnpm install --frozen-lockfile

    # Workaround for parallel building with forge:
    # https://github.com/foundry-rs/foundry/issues/4736
    - name: Setup forge
      working-directory: packages/schema-type
      run: forge build
