name: Setup prerequisites
description: Setup pnpm, Node.js, and Foundry
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Setup node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Setup node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Setup foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
