name: Build WSL

# Verifies build artifacts in pull requests.
# Note: this workflow does not trigger on pushes to main,
# because the release workflow includes a build+verify step.
on:
  pull_request:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    name: Build and validate artifacts
    defaults:
      run:
        shell: wsl-bash {0}
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check for changes outside docs
        id: check_changes
        run: ./.github/scripts/check_changes_outside_docs.sh

      - name: setup WSL for Windows runner
        uses: Vampire/setup-wsl@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Setup foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install node dependencies
        run: pnpm install --frozen-lockfile

      # Workaround for parallel building with forge:
      # https://github.com/foundry-rs/foundry/issues/4736
      - name: Setup forge
        working-directory: packages/schema-type
        run: forge build

      # - name: Setup
      #   if: steps.check_changes.outputs.changes_outside_docs
      #   uses: ./.github/actions/setup

      - name: Clean
        if: steps.check_changes.outputs.changes_outside_docs
        run: pnpm turbo run clean --concurrency 10

      - name: Build
        if: steps.check_changes.outputs.changes_outside_docs
        run: pnpm turbo run build --concurrency 10

      - name: Outdated files, run `pnpm build` and commit them
        if: steps.check_changes.outputs.changes_outside_docs
        uses: ./.github/actions/require-empty-diff

      - name: Build API docs
        if: steps.check_changes.outputs.changes_outside_docs
        run: pnpm docs:generate:api

      # - name: Outdated files, run `pnpm docs:generate:api` and commit them
      #   if: steps.check_changes.outputs.changes_outside_docs
      #   uses: ./.github/actions/require-empty-diff
